name: Java CI with Maven

on:
  push:
    branches: [ main , test ]
  pull_request:
    branches: [ main , test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      # - name: Build with Maven
      #   run: mvn -B -DskipTests=true package -P prod --file pom.xml

      # - name: Copy files
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     key: ${{ secrets.KEY }}
      #     source: "target/app.jar"
      #     target: "~/blog/server"

      - name: Run Deploy
        uses: appleboy/ssh-action@master
        env:
          MODE: ${{ secrets.MODE }} 
          PORT: ${{ secrets.PORT }} 
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        with:
          envs: MYSQL_USERNAME,MYSQL_PASSWORD,MODE,PORT
          command_timeout: 4m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/blog/server

            pid=$(lsof -t -i:$PORT)
            echo "pid: $pid"
            kill -9 $pid

            # rm -rf app.jar
            # mv target/app.jar app.jar
            # rm -rf target

            nohup java -jar app.jar --MYSQL_USERNAME=$MYSQL_USERNAME --MYSQL_PASSWORD=$MYSQL_PASSWORD --MODE=$MODE
